/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Falah (https://sketchfab.com/falah01)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pubg-hyundai-pony-coupe-8903771b596146bcb0bf7747bf78fa5f
title: PUBG : HYUNDAI Pony Coupe
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/car-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_71.geometry} material={materials.M_PonyCoupe_Body_01} skeleton={nodes.Object_71.skeleton} />
            <skinnedMesh geometry={nodes.Object_72.geometry} material={materials.M_PonyCoupe_Bulb_01} skeleton={nodes.Object_72.skeleton} />
            <skinnedMesh geometry={nodes.Object_73.geometry} material={materials.M_PonyCoupe_Interior_01} skeleton={nodes.Object_73.skeleton} />
            <skinnedMesh geometry={nodes.Object_74.geometry} material={materials.M_PonyCoupe_Panel_01} skeleton={nodes.Object_74.skeleton} />
            <skinnedMesh geometry={nodes.Object_75.geometry} material={materials.M_PonyCoupe_Chassis_01} skeleton={nodes.Object_75.skeleton} />
            <skinnedMesh geometry={nodes.Object_76.geometry} material={materials.M_PonyCoupe_Wheel_01} skeleton={nodes.Object_76.skeleton} />
            <skinnedMesh geometry={nodes.Object_77.geometry} material={materials.M_PonyCoupe_Glass_01} skeleton={nodes.Object_77.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
