import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import Image from "next/image";
import { Suspense } from "react";
import styles from "../styles/Home.module.css";
import Elements from "../components/Elements";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Canvas className={styles.three_canvas} shadows>
        <Suspense fallback={null}>
          <Elements />
        </Suspense>
      </Canvas>
    </div>
  );
}
